########################################################
#                   NAS PARAMETERS                     #
########################################################
CONTROLLER_SAMPLING_EPOCHS: 10
SAMPLES_PER_CONTROLLER_EPOCH: 10
CONTROLLER_TRAINING_EPOCHS: 10
ARCHITECTURE_TRAINING_EPOCHS: 10
CONTROLLER_LOSS_ALPHA: 10

########################################################
#               CONTROLLER PARAMETERS                  #
########################################################
CONTROLLER_LSTM_DIM: 100
CONTROLLER_OPTIMIZER: 'Adam'
CONTROLLER_LEARNING_RATE: 0.01
CONTROLLER_DECAY: 0.1
CONTROLLER_MOMENTUM: 0.0
CONTROLLER_USE_PREDICTOR: True

########################################################
#                   MLP PARAMETERS                     #
########################################################
MAX_ARCHITECTURE_LENGTH: 3
MLP_OPTIMIZER: 'Adam' #sgd,
MLP_LEARNING_RATE: 0.01
MLP_DECAY: 0.0
MLP_MOMENTUM: 0.0
MLP_DROPOUT: 0.2
MLP_LOSS_FUNCTION: 'mean_squared_error' #kl_divergence, categorical_crossentropy (https://www.tensorflow.org/api_docs/python/tf/keras/metrics/kl_divergence)
MLP_ONE_SHOT: True
nodes: [8, 16, 32, 64, 128, 256, 512]
activation_functions: ['sigmoid', 'tanh', 'relu', 'elu']

########################################################
#                   DATA PARAMETERS                    #
########################################################
TARGET_CLASSES: 2
IS_TARGET_CATEGORICAL: no
CLASS_COLUMN: "Class"
CSV_TRAINING: "/home/giacomo/Scaricati/MLPNAS-master/DATASETS/training_e_IA.csv"
CSV_TESTING: "/home/giacomo/Scaricati/MLPNAS-master/DATASETS/testing_e_IA.csv"

########################################################
#                  OUTPUT PARAMETERS                   #
########################################################
TOP_N: 5
METRICS: ['precision']        #['accuracy'] ['precision'] ['f1score']
TARGET_SCORE: 'val_precision' #val_accuracy, val_f1_score